Update pyproject.toml
Fixed 
```
error: Failed to parse entry in group `test`: `kvikio-cu12>=25.02.01; platform_system == "Linux" & python_version >= 3.10`
  Caused by: Unexpected character '&', expected 'and', 'or' or end of input
kvikio-cu12>=25.02.01; platform_system == "Linux" & python_version >= 3.10
```